# Generated by Django 4.0.8 on 2022-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1),
        ),
    ]
